@startuml
actor User
participant "Oxygen\nXML Editor" as Oxygen
participant "ediarum.webdav" as Webdav
database "Git Repository" as Git

User -> Oxygen : edits XML
Oxygen -> Webdav : saves XML via HTTP WebDAV
Webdav -> Webdav : saves files
Webdav -> Git : writes git commit
@enduml
